### ISSUE TITLE
Fourier feature equation

### ISSUE THREAD

**Issue by smao-astro** [PredictiveIntelligenceLab/MultiscalePINNs#1]
Hi,

Thank you very much for make the code available.

In the Fourier feature part, such as https://github.com/PredictiveIntelligenceLab/MultiscalePINNs/blob/325b62c929d55028de848d8884e4c59377e68754/Poisson1D/models_tf.py#L310-L316
and all the other part, seems that you are doing `cos(b * x), sin(b * x)`, however, in the [initial paper](https://arxiv.org/abs/2006.10739) and [your paper](https://arxiv.org/abs/2012.10047), is `cos(2 * pi * b * x), sin(2 * pi * b * x)`, I know it is only a difference of factor, but would you like to explain which one gives the result of your paper?

Thanks.

**Comment by paraklas** [comment]
Thanks for the comment. The `2*pi` factor shouldn't play a big role -- its effect can be absorbed in the frequency used to initialize the Fourier features. The results reported in the paper correspond to the code provided here, i.e. using `cos(b * x), sin(b * x)`.

**Comment by smao-astro** [comment]
I see, thank you.
